name: Windows - LiteManager
on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    steps:
      - name: Downloading & installing Essentials
        run: |
          $url = "https://github.com/correct-username/repo-name/raw/branch-name/Downloads.bat"  # Replace with valid URL
          Invoke-WebRequest -Uri $url -OutFile "Downloads.bat"
          if (Test-Path "Downloads.bat") {
            cmd /c Downloads.bat
          } else {
            Write-Error "Failed to download Downloads.bat"
          }
      - name: Connect to LiteManager
        run: cmd /c show.bat
        if: success()  # Only run if previous step succeeds
      - name: Time Counter
        run: cmd /c loop.bat
        if: success()  # Only run if previous step succeeds
